from pathlib import Path
import json, re

p=Path('game-detail-enhancement.js')
s=p.read_text(encoding='utf-8')

old_base = r"""  function currentBaseState(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    const status = String(detail?.status || '').toLowerCase();
    if (status === 'final' || inferredOutsAfterPlay(last) >= 3) return [false,false,false];
    const league=String(detail?.league || '').toUpperCase();
    if (league === 'CPBL' && last) {
      const currentName=compactName(detail?.current?.batter?.fullName||detail?.current?.batter?.name||'');
      const lastName=compactName(last?.batter?.fullName||last?.batter?.name||last?.batter||last?.hitter||'');
      // CPBL may keep the completed hitter as current until the next PA starts.
      // In that gap, use the post-PA state generated by the shared cache.
      if (currentName && lastName && samePlayerName(currentName,lastName)) {
        if (last?.baseStateAfter !== undefined && last?.baseStateAfter !== null) return last.baseStateAfter;
        if (last?.basesAfter) return last.basesAfter;
      }
    }
    if (league === 'NPB') {
      const inferred = inferRunnerNames(detail);
      if (inferred.first || inferred.second || inferred.third) {
        return [!!inferred.first, !!inferred.second, !!inferred.third];
      }
      if (detail?.current?.bases !== undefined && detail?.current?.bases !== null) return detail.current.bases;
    }
    if (detail?.current?.baseState) return detail.current.baseState;
    if (detail?.current?.bases) return detail.current.bases;
    return last?.baseStateAfter || last?.basesAfter || last?.baseState || last?.bases || '';
  }
"""
new_base = r"""  function baseStateKey(value) {
    const s=normalizeBaseState(value);
    return `${s.first?'1':'0'}${s.second?'1':'0'}${s.third?'1':'0'}`;
  }

  function shouldUseCpblLastAfter(detail,last) {
    if(String(detail?.league||'').toUpperCase()!=='CPBL' || !last) return false;
    const hasAfter=last?.baseStateAfter!==undefined&&last?.baseStateAfter!==null || !!last?.basesAfter;
    if(!hasAfter) return false;
    const currentName=compactName(detail?.current?.batter?.fullName||detail?.current?.batter?.name||'');
    const lastName=compactName(last?.batter?.fullName||last?.batter?.name||last?.batter||last?.hitter||'');
    if(currentName && lastName && samePlayerName(currentName,lastName)) return true;

    const beforeValue=last?.baseState ?? last?.bases ?? '';
    const afterValue=last?.baseStateAfter ?? last?.basesAfter ?? '';
    const currentValue=detail?.current?.baseState ?? detail?.current?.bases ?? '';
    const beforeKey=baseStateKey(beforeValue), afterKey=baseStateKey(afterValue), currentKey=baseStateKey(currentValue);

    // CPBL can advance current.batter before current.baseState catches up.
    // If current still equals the completed PA's pre-PA state while the post-PA
    // state changed, the post-PA state is the authoritative live situation.
    return beforeKey!==afterKey && currentKey===beforeKey;
  }

  function currentBaseState(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    const status = String(detail?.status || '').toLowerCase();
    if (status === 'final' || inferredOutsAfterPlay(last) >= 3) return [false,false,false];
    const league=String(detail?.league || '').toUpperCase();
    if (league === 'CPBL' && shouldUseCpblLastAfter(detail,last)) {
      if (last?.baseStateAfter !== undefined && last?.baseStateAfter !== null) return last.baseStateAfter;
      if (last?.basesAfter) return last.basesAfter;
    }
    if (league === 'NPB') {
      const inferred = inferRunnerNames(detail);
      if (inferred.first || inferred.second || inferred.third) {
        return [!!inferred.first, !!inferred.second, !!inferred.third];
      }
      if (detail?.current?.bases !== undefined && detail?.current?.bases !== null) return detail.current.bases;
    }
    if (detail?.current?.baseState) return detail.current.baseState;
    if (detail?.current?.bases) return detail.current.bases;
    return last?.baseStateAfter || last?.basesAfter || last?.baseState || last?.bases || '';
  }
"""
if old_base not in s:
    raise SystemExit('currentBaseState anchor missing')
s=s.replace(old_base,new_base,1)

old_runner = r"""  function currentRunnerNames(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    if (String(detail?.status || '').toLowerCase() === 'final' || inferredOutsAfterPlay(last) >= 3) {
      return {first:'',second:'',third:''};
    }
    const direct = directRunnerNames(detail), inferred = inferRunnerNames(detail);
    let immediate={first:'',second:'',third:''};
    if(String(detail?.league||'').toUpperCase()==='CPBL' && last){
      const currentName=compactName(detail?.current?.batter?.fullName||detail?.current?.batter?.name||'');
      const lastName=compactName(last?.batter?.fullName||last?.batter?.name||last?.batter||last?.hitter||'');
      if(currentName&&lastName&&samePlayerName(currentName,lastName)){
        const raw=last?.runnersAfter||{};
        immediate={first:compactName(raw.first||''),second:compactName(raw.second||''),third:compactName(raw.third||'')};
      }
    }
    const merged={first:direct.first||immediate.first||inferred.first,second:direct.second||immediate.second||inferred.second,third:direct.third||immediate.third||inferred.third};
    const state=normalizeBaseState(currentBaseState(detail));
    return {first:state.first?merged.first:'',second:state.second?merged.second:'',third:state.third?merged.third:''};
  }
"""
new_runner = r"""  function currentRunnerNames(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    if (String(detail?.status || '').toLowerCase() === 'final' || inferredOutsAfterPlay(last) >= 3) {
      return {first:'',second:'',third:''};
    }
    const direct = directRunnerNames(detail), inferred = inferRunnerNames(detail);
    let immediate={first:'',second:'',third:''};
    const useCpblAfter=shouldUseCpblLastAfter(detail,last);
    if(useCpblAfter){
      const raw=last?.runnersAfter||{};
      immediate={first:compactName(raw.first||''),second:compactName(raw.second||''),third:compactName(raw.third||'')};
    }
    // When current.baseState is stale, its runner names are stale as well.
    // Prefer the completed PA's post-state identities before direct current runners.
    const merged=useCpblAfter
      ? {first:immediate.first||direct.first||inferred.first,second:immediate.second||direct.second||inferred.second,third:immediate.third||direct.third||inferred.third}
      : {first:direct.first||inferred.first,second:direct.second||inferred.second,third:direct.third||inferred.third};
    const state=normalizeBaseState(currentBaseState(detail));
    return {first:state.first?merged.first:'',second:state.second?merged.second:'',third:state.third?merged.third:''};
  }
"""
if old_runner not in s:
    raise SystemExit('currentRunnerNames anchor missing')
s=s.replace(old_runner,new_runner,1)

old_stamp = r"""      JSON.stringify(detail?.current?.runners||{}),JSON.stringify(detail?.current?.baseState||{}),detail?.current?.bases,last?.inning,last?.half,last?.batter,last?.pitcher,last?.result,last?.bases,last?.rbi].map(v=>String(v??'')).join('|');
"""
new_stamp = r"""      JSON.stringify(detail?.current?.runners||{}),JSON.stringify(detail?.current?.baseState||{}),detail?.current?.bases,last?.inning,last?.half,last?.batter,last?.pitcher,last?.result,last?.bases,last?.rbi,
      JSON.stringify(last?.baseStateAfter||{}),JSON.stringify(last?.runnersAfter||{})].map(v=>String(v??'')).join('|');
"""
if old_stamp not in s:
    raise SystemExit('detailStamp anchor missing')
s=s.replace(old_stamp,new_stamp,1)
p.write_text(s,encoding='utf-8')

for name in [
    'app.js','index.html','styles.css','cpbl-realtime.js','npb-realtime.js',
    'service-worker.js','diagnostics.html','game-detail-enhancement.js',
    'game-detail-enhancement.css','report-layout.js','report-layout.css',
    'postseason-history.js','landscape-state.js','landscape-state.css',
    'cpbl-cache-router.js','live-static-update.js'
]:
    q=Path(name)
    if not q.exists(): continue
    x=q.read_text(encoding='utf-8').replace('v3.01','v3.02').replace('v301','v302')
    if name=='service-worker.js':
        x=re.sub(r'baseball-player-card-pwa-v\d+','baseball-player-card-pwa-v302',x)
    q.write_text(x,encoding='utf-8')
Path('version.json').write_text(json.dumps({'version':'v3.02'},ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')

for old_path in [
    '.github/scripts/apply_v300.py',
    '.github/scripts/smoke_v300.mjs',
    '.github/workflows/apply-v300.yml',
]:
    Path(old_path).unlink(missing_ok=True)

print('v3.02 CPBL post-PA runner fallback applied')
