from pathlib import Path
import json, re

p=Path('game-detail-enhancement.js')
s=p.read_text(encoding='utf-8')

old_base="""  function currentBaseState(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    const status = String(detail?.status || '').toLowerCase();
    if (status === 'final' || inferredOutsAfterPlay(last) >= 3) return [false,false,false];
    if (String(detail?.league || '').toUpperCase() === 'NPB') {
      const inferred = inferRunnerNames(detail);
      if (inferred.first || inferred.second || inferred.third) {
        return [!!inferred.first, !!inferred.second, !!inferred.third];
      }
      if (detail?.current?.bases !== undefined && detail?.current?.bases !== null) return detail.current.bases;
    }
    if (detail?.current?.baseState) return detail.current.baseState;
    if (detail?.current?.bases) return detail.current.bases;
    return last?.baseState || last?.basesAfter || last?.bases || '';
  }
"""
new_base="""  function currentBaseState(detail) {
    const plays = Array.isArray(detail?.plays) ? detail.plays : [];
    const last = plays[plays.length - 1];
    const status = String(detail?.status || '').toLowerCase();
    if (status === 'final' || inferredOutsAfterPlay(last) >= 3) return [false,false,false];
    const league=String(detail?.league || '').toUpperCase();
    if (league === 'CPBL' && last) {
      const currentName=compactName(detail?.current?.batter?.fullName||detail?.current?.batter?.name||'');
      const lastName=compactName(last?.batter?.fullName||last?.batter?.name||last?.batter||last?.hitter||'');
      // CPBL may keep the completed hitter as current until the next PA starts.
      // In that gap, use the post-PA state generated by the shared cache.
      if (currentName && lastName && samePlayerName(currentName,lastName)) {
        if (last?.baseStateAfter !== undefined && last?.baseStateAfter !== null) return last.baseStateAfter;
        if (last?.basesAfter) return last.basesAfter;
      }
    }
    if (league === 'NPB') {
      const inferred = inferRunnerNames(detail);
      if (inferred.first || inferred.second || inferred.third) {
        return [!!inferred.first, !!inferred.second, !!inferred.third];
      }
      if (detail?.current?.bases !== undefined && detail?.current?.bases !== null) return detail.current.bases;
    }
    if (detail?.current?.baseState) return detail.current.baseState;
    if (detail?.current?.bases) return detail.current.bases;
    return last?.baseStateAfter || last?.basesAfter || last?.baseState || last?.bases || '';
  }
"""
if old_base not in s: raise SystemExit('currentBaseState anchor missing')
s=s.replace(old_base,new_base,1)

old_outs="""  function inferredOutsAfterPlay(play) {
    if (!play) return 0;
    const before = parseOutNumber(play.outs);
    if (before === null) return 0;
    const text = `${play.raw || ''} ${play.result || ''} ${play.description || ''}`;
    if (/3\\s*人出局|三人出局|3\\s*出局/i.test(text)) return 3;
    let added = 0;
    if (/三殺|トリプルプレー/i.test(text)) added = 3;
    else if (/雙殺|併殺|ダブルプレー|DP\\b/i.test(text)) added = 2;
    else if (/三振|ゴロ|滾地|フライ|飛球|ライナー|平飛|犧牲|犠牲|犠打|アウト|出局/i.test(text)) added = 1;
    return Math.min(3, before + added);
  }
"""
new_outs="""  function inferredOutsAfterPlay(play) {
    if (!play) return 0;
    const before = parseOutNumber(play.outs);
    if (before === null) return 0;
    const resultText=`${play.result || ''} ${play.raw || ''}`;
    const description=String(play.description || '');
    const text=`${resultText} ${description}`;
    const explicit=text.match(/([0-3])\\s*人出局/i);
    if (explicit) return Math.min(3,Number(explicit[1]));
    if (/三人出局|3\\s*出局/i.test(text)) return 3;
    // A hit can contain words such as '高飛球' in its description; that is not an out.
    if (/全壘打|三壘安打|二壘安打|一壘安打|安打|四壞|故意四壞|觸身|死球|失誤上壘|野手選擇|趁傳上壘/i.test(resultText)) return before;
    let added = 0;
    if (/三殺|トリプルプレー/i.test(resultText)) added = 3;
    else if (/雙殺|併殺|ダブルプレー|DP\\b/i.test(resultText)) added = 2;
    else if (/三振|ゴロ|滾地|一滾|二滾|三滾|游滾|遊滾|投滾|捕滾|フライ|飛球|界飛|ライナー|平飛|犧牲|犠牲|犠打|犧飛|アウト|出局/i.test(resultText)) added = 1;
    else if (/打者[^。]*(刺殺|接殺|封殺|出局)/i.test(description)) added = 1;
    return Math.min(3, before + added);
  }
"""
if old_outs not in s: raise SystemExit('inferredOutsAfterPlay anchor missing')
s=s.replace(old_outs,new_outs,1)

old_current="""    const direct = directRunnerNames(detail), inferred = inferRunnerNames(detail);
    const merged={first:direct.first||inferred.first,second:direct.second||inferred.second,third:direct.third||inferred.third};
    const hasOfficialState=detail?.current?.baseState!==undefined&&detail?.current?.baseState!==null
      || (detail?.current?.bases!==undefined&&detail?.current?.bases!==null&&String(detail.current.bases).trim()!=='');
    if(!hasOfficialState) return merged;
    const state=normalizeBaseState(detail?.current?.baseState ?? detail?.current?.bases ?? '');
    return {first:state.first?merged.first:'',second:state.second?merged.second:'',third:state.third?merged.third:''};
"""
new_current="""    const direct = directRunnerNames(detail), inferred = inferRunnerNames(detail);
    let immediate={first:'',second:'',third:''};
    if(String(detail?.league||'').toUpperCase()==='CPBL' && last){
      const currentName=compactName(detail?.current?.batter?.fullName||detail?.current?.batter?.name||'');
      const lastName=compactName(last?.batter?.fullName||last?.batter?.name||last?.batter||last?.hitter||'');
      if(currentName&&lastName&&samePlayerName(currentName,lastName)){
        const raw=last?.runnersAfter||{};
        immediate={first:compactName(raw.first||''),second:compactName(raw.second||''),third:compactName(raw.third||'')};
      }
    }
    const merged={first:direct.first||immediate.first||inferred.first,second:direct.second||immediate.second||inferred.second,third:direct.third||immediate.third||inferred.third};
    const state=normalizeBaseState(currentBaseState(detail));
    return {first:state.first?merged.first:'',second:state.second?merged.second:'',third:state.third?merged.third:''};
"""
if old_current not in s: raise SystemExit('currentRunnerNames anchor missing')
s=s.replace(old_current,new_current,1)

pitcher_anchor="""  function currentPitcherSummary(detail,side) {
"""
prev_fn="""  function previousPlateAppearance(detail) {
    const plays=Array.isArray(detail?.plays)?detail.plays:[];
    const play=plays.at(-1)||null;
    if(!play) return {name:'',result:''};
    const name=compactName(play?.batter?.fullName||play?.batter?.name||play?.batter||play?.hitter?.fullName||play?.hitter?.name||play?.hitter||'');
    return {name,result:shortPaResult(play)};
  }

"""
if pitcher_anchor not in s: raise SystemExit('currentPitcherSummary anchor missing')
s=s.replace(pitcher_anchor,prev_fn+pitcher_anchor,1)

old_runner_head="""    const pitcher=currentPitcherSummary(detail,defenseSide), batter=currentBatterPaSummary(detail);
    const paHtml=batter.results.length?batter.results.map((result,i)=>`<span title=\"第${i+1}打席\">${esc(result)}</span>`).join(''):'<span class=\"is-empty\">尚未有打席</span>';
"""
new_runner_head="""    const pitcher=currentPitcherSummary(detail,defenseSide), batter=currentBatterPaSummary(detail), previous=previousPlateAppearance(detail);
    const paHtml=batter.results.length?batter.results.map((result,i)=>`<span title=\"第${i+1}打席\">${esc(result)}</span>`).join(''):'<span class=\"is-empty\">尚未有打席</span>';
    const prevHtml=previous.name?`<div class=\"gdx-live-previous-row\"><span>上一棒</span><strong>${esc(previous.name)}</strong><b>${esc(previous.result||'—')}</b></div>`:'';
"""
if old_runner_head not in s: raise SystemExit('renderRunnerDiamond head anchor missing')
s=s.replace(old_runner_head,new_runner_head,1)
old_tail='<div class="gdx-pa-results">${paHtml}</div></div></div></div>'; new_tail='<div class="gdx-pa-results">${paHtml}</div></div>${prevHtml}</div></div>'
if old_tail not in s: raise SystemExit('renderRunnerDiamond tail anchor missing')
s=s.replace(old_tail,new_tail,1)
p.write_text(s,encoding='utf-8')

# Landscape styling for the previous-batter strip.
p=Path('game-detail-enhancement.css')
css=p.read_text(encoding='utf-8')
css += """

/* ===== v3.01 PREVIOUS BATTER ===== */
@media (orientation:landscape) and (min-width:700px){
  .gdx-live-previous-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:6px;min-width:0;padding-top:5px;border-top:1px solid rgba(255,255,255,.08)}
  .gdx-live-previous-row>span{font-size:8px;font-weight:900;letter-spacing:.08em;color:#86a6c7}
  .gdx-live-previous-row>strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;font-weight:900;color:#dce9f5}
  .gdx-live-previous-row>b{padding:3px 6px;border:1px solid rgba(98,214,196,.28);border-radius:6px;background:rgba(98,214,196,.08);font-size:9px;font-weight:900;color:#9af2e5;white-space:nowrap}
}
@media (orientation:landscape) and (min-width:700px) and (max-width:980px){
  .gdx-live-previous-row{gap:4px;padding-top:3px}
  .gdx-live-previous-row>strong{font-size:8px}
  .gdx-live-previous-row>b{font-size:7px;padding:2px 4px}
}
/* ===== v3.01 PREVIOUS BATTER END ===== */
"""
p.write_text(css,encoding='utf-8')

# Formal version bump.
for name in [
    'app.js','index.html','styles.css','cpbl-realtime.js','npb-realtime.js',
    'service-worker.js','diagnostics.html','game-detail-enhancement.js',
    'game-detail-enhancement.css','report-layout.js','report-layout.css',
    'postseason-history.js','landscape-state.js','landscape-state.css',
    'cpbl-cache-router.js','live-static-update.js'
]:
    q=Path(name)
    if not q.exists(): continue
    x=q.read_text(encoding='utf-8').replace('v3.00','v3.01').replace('v300','v301')
    if name=='service-worker.js': x=re.sub(r'baseball-player-card-pwa-v\d+','baseball-player-card-pwa-v301',x)
    q.write_text(x,encoding='utf-8')
Path('version.json').write_text(json.dumps({'version':'v3.01'},ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')

# Keep only current + immediately previous release artifacts.
for old_path in [
    '.github/scripts/apply_v299.py',
    '.github/scripts/smoke_v299.mjs',
    '.github/workflows/apply-v299.yml',
]:
    Path(old_path).unlink(missing_ok=True)

print('v3.01 CPBL immediate runner state + previous batter applied')
