const BASE='https://cpbl.com.tw';
const PROXY_KEY_SHA256='__CPBL_PROXY_KEY_SHA256__';
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','accept-language':'zh-TW,zh;q=0.9,en;q=0.8','accept':'application/json, text/javascript, */*; q=0.01'};
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type, x-cpbl-proxy-key','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8'};
const json=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:CORS});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function sha256(v:string){const d=new TextEncoder().encode(v);const h=await crypto.subtle.digest('SHA-256',d);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cleanName(v=''){return String(v).replace(/^[＃#*＊\s]+/,'').trim();}
function textBetween(html:string,re:RegExp){return html.match(re)?.[1]?.replace(/<[^>]+>/g,'').trim()||'';}
function cookieHeader(res:Response){try{const a=(res.headers as any).getSetCookie?.();if(Array.isArray(a)&&a.length)return a.map((x:string)=>x.split(';')[0]).filter(Boolean).join('; ');}catch{}const raw=res.headers.get('set-cookie')||'';return raw.split(/,(?=\s*[^;,=\s]+=[^;,]*)/).map(x=>x.trim().split(';')[0]).filter(Boolean).join('; ');}
function csrfFrom(html:string){return html.match(/RequestVerificationToken:\s*['\"]([^'\"]+)['\"]/)?.[1]||html.match(/name=["']__RequestVerificationToken["'][^>]*value=["']([^"']+)/)?.[1]||'';}
function retryable(e:any){const m=e instanceof Error?e.message:String(e||'');return /CPBL (?:GET|POST).*\b(?:403|429|502|503|504)\b/.test(m)||/回傳非 JSON/.test(m);}
async function getHtml(path:string,attempts=2){let last:any;for(let i=1;i<=attempts;i++){try{const r=await fetch(BASE+path,{headers:{...HEADERS,accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'},redirect:'follow'}),html=await r.text();if(!r.ok)throw new Error(`CPBL GET ${path} ${r.status}`);return{html,cookie:cookieHeader(r)};}catch(e){last=e;if(i===attempts||!retryable(e))throw e;await sleep(220*i);}}throw last;}
async function postForm(path:string,data:Record<string,string>,opts:{referer?:string,token?:string,cookie?:string}={}){const h:any={...HEADERS,'x-requested-with':'XMLHttpRequest','content-type':'application/x-www-form-urlencoded; charset=UTF-8',referer:opts.referer||BASE+'/',origin:BASE};if(opts.token)h.RequestVerificationToken=opts.token;if(opts.cookie)h.cookie=opts.cookie;const r=await fetch(BASE+path,{method:'POST',headers:h,body:new URLSearchParams(data),redirect:'follow'}),txt=await r.text();if(!r.ok)throw new Error(`CPBL POST ${path} ${r.status}`);try{return JSON.parse(txt)}catch{throw new Error(`CPBL ${path} 回傳非 JSON`)}}
async function postSession(pagePath:string,postPath:string,data:Record<string,string>,tokenRequired=true){let last:any;for(let i=1;i<=2;i++){try{const page=await getHtml(pagePath,2),token=tokenRequired?csrfFrom(page.html):'';if(tokenRequired&&!token)throw new Error(`找不到 CPBL ${postPath} 查詢 token`);return await postForm(postPath,data,{referer:BASE+pagePath,token,cookie:page.cookie});}catch(e){last=e;if(i===2||!retryable(e))throw e;await sleep(300*i);}}throw last;}
function num(o:any,...ks:string[]){for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!==''){const n=Number(o[k]);if(Number.isFinite(n))return n;}return 0;}
function str(o:any,...ks:string[]){for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null)return String(o[k]);return'';}
function normalizeKind(v:any){return String(v||'A').toUpperCase()==='D'?'D':'A';}
function baseballIpToOuts(v:any){const m=String(v??'0').trim().match(/^(\d+)(?:\.([012]))?$/);return m?Number(m[1])*3+Number(m[2]||0):0;}
async function profile(acnt:string){const{html}=await getHtml(`/team/person?acnt=${encodeURIComponent(acnt)}`);const team=textBetween(html,/<div class="team">([\s\S]*?)<\/div>/i),name=textBetween(html,/<div class="name">\s*([^<]*?)(?:<span|<\/div>)/i),number=textBetween(html,/<span class="number">([\s\S]*?)<\/span>/i),position=textBetween(html,/<dd class="pos">[\s\S]*?<div class="desc">([\s\S]*?)<\/div>/i),teamCode=html.match(/\/team\?ClubNo=([A-Z]{3})/)?.[1]||'';return{acnt,name:cleanName(name),number,team,teamCode,position};}
async function searchPlayer(name:string,number:string){const{html}=await getHtml('/player'),re=/<a href="\/team\/person\?acnt=([0-9]+)"[^>]*>([^<]+)<\/a>/gi,c:any[]=[];let m:RegExpExecArray|null;while((m=re.exec(html))){const n=cleanName(m[2]);if(n===name||n.includes(name))c.push({acnt:m[1],name:n});}for(const x of c){const p=await profile(x.acnt);if(p.number===number&&p.name===name)return p;}for(const x of c){const p=await profile(x.acnt);if(p.number===number)return p;}return null;}
async function suggestPlayers(query:string,limit=10){const q=cleanName(query);if(!q)return[];const{html}=await getHtml('/player'),re=/<a href="\/team\/person\?acnt=([0-9]+)"[^>]*>([^<]+)<\/a>/gi,seen=new Set<string>(),a:any[]=[],b:any[]=[],c:any[]=[];let m:RegExpExecArray|null;while((m=re.exec(html))){const acnt=String(m[1]),name=cleanName(m[2]);if(!acnt||!name||seen.has(acnt)||!name.includes(q))continue;seen.add(acnt);const x={acnt,name};if(name===q)a.push(x);else if(name.startsWith(q))b.push(x);else c.push(x);}return[...a,...b,...c].slice(0,Math.max(1,Math.min(20,Number(limit)||10)));}
async function seasonEndpoint(acnt:string,kind:string,path:string){return await postSession(`/team/person?acnt=${encodeURIComponent(acnt)}`,path,{acnt,kindCode:normalizeKind(kind)},true);}
function normalizeSeason(bat:any,pit:any,kind:string,be='',pe=''){const batting=bat?{pa:num(bat,'PlateAppearances'),ab:num(bat,'HitCnt'),rbi:num(bat,'RunBattedINCnt'),runs:num(bat,'ScoreCnt'),single:num(bat,'OneBaseHitCnt'),double:num(bat,'TwoBaseHitCnt'),triple:num(bat,'ThreeBaseHitCnt'),hr:num(bat,'HomeRunCnt'),sacBunt:num(bat,'SacrificeHitCnt'),sacFly:num(bat,'SacrificeFlyCnt'),bb:num(bat,'BasesONBallsCnt'),ibb:num(bat,'IntentionalBasesONBallsCnt'),hbp:num(bat,'HitBYPitchCnt')}:null;const pitching=pit?{cg:num(pit,'CompleteGames'),sho:num(pit,'ShoutOut'),noWalkHbp:num(pit,'NoBaseBalled'),w:num(pit,'Wins'),l:num(pit,'Loses'),sv:num(pit,'SaveOK'),bsv:num(pit,'SaveFail'),hld:num(pit,'ReliefPointCnt'),outs:baseballIpToOuts(pit.InningPitched),innings:str(pit,'InningPitched'),h:num(pit,'HittingCnt'),bb:num(pit,'BasesONBallsCnt')+num(pit,'IntentionalBasesONBallsCnt'),hbp:num(pit,'HitBYPitchCnt'),k:num(pit,'StrikeOutCnt'),er:num(pit,'EarnedRunCnt')}:null;return{kindCode:kind,batting,pitching,raw:{batting:bat,pitching:pit},partialErrors:{batting:be||null,pitching:pe||null}};}
async function seasonHistory(acnt:string,kind='A'){kind=normalizeKind(kind);let br:any=null,pr:any=null,be='',pe='';try{br=await seasonEndpoint(acnt,kind,'/team/getbattingscore')}catch(e){be=e instanceof Error?e.message:String(e)}await sleep(120);try{pr=await seasonEndpoint(acnt,kind,'/team/getpitchscore')}catch(e){pe=e instanceof Error?e.message:String(e)}if(!br&&!pr)throw new Error([be,pe].filter(Boolean).join('；')||'CPBL 成績查詢失敗');const bs=br?.Success?JSON.parse(br.BattingScore||'[]'):[],ps=pr?.Success?JSON.parse(pr.PitchScore||pr.PitchingScore||'[]'):[],years=[...new Set([...bs.map((r:any)=>Number(r.Year)),...ps.map((r:any)=>Number(r.Year))].filter((y:number)=>Number.isInteger(y)&&y>=1990&&y<=2100))].sort((a:number,b:number)=>b-a),seasons=years.map((year:number)=>({year,...normalizeSeason(bs.find((r:any)=>Number(r.Year)===year)||null,ps.find((r:any)=>Number(r.Year)===year)||null,kind,be,pe)}));return{kindCode:kind,years,seasons,partialErrors:{batting:be||null,pitching:pe||null}};}
async function seasonHistories(acnt:string){const histories:any={},errors:any={};for(const k of ['A','D']){try{histories[k]=await seasonHistory(acnt,k);errors[k]=null;}catch(e){histories[k]=null;errors[k]=e instanceof Error?e.message:String(e);}}if(!histories.A&&!histories.D)throw new Error([errors.A,errors.D].filter(Boolean).join('；'));return{histories,errors};}
async function seasonStats(acnt:string,year:number,kind='A'){const h=await seasonHistory(acnt,kind),s=h.seasons.find((x:any)=>Number(x.year)===year)||null;return s?{kindCode:h.kindCode,batting:s.batting,pitching:s.pitching,raw:s.raw,partialErrors:s.partialErrors}:{kindCode:h.kindCode,batting:null,pitching:null,raw:{batting:null,pitching:null},partialErrors:h.partialErrors};}
function chinese(v:string){const map:any={'零':0,'〇':0,'一':1,'二':2,'兩':2,'三':3,'四':4};return /^\d+$/.test(String(v||''))?Number(v):map[String(v||'').trim()]??0;}
function pa(action:string,content:string){const a=String(action||'').trim(),all=a+String(content||'').trim(),o:any={code:'',position:'',rbi:0,officialAction:a};if(/內全|全壘打|全打/.test(all))o.code='HR';else if(/內三|場三|三壘安打|三安/.test(a))o.code='3B';else if(/內二|場二|二壘安打|二安/.test(a))o.code='2B';else if(/內安|場安|一壘安打|一安|安打/.test(a))o.code='1B';else if(/不死三振/.test(all))o.code='KREACH';else if(/故意四壞|故四/.test(all))o.code='IBB';else if(/四壞/.test(all))o.code='BB';else if(/觸身|死球/.test(all))o.code='HBP';else if(/礙打|打擊妨礙/.test(all))o.code='CI';else if(/雙殺/.test(all))o.code='DP';else if(/三殺/.test(all))o.code='TP';else if(/犧短誤|犧選誤|犧選|犧牲短打|犧短/.test(all))o.code='SH';else if(/界犧飛|犧飛誤|犧牲飛球|犧飛/.test(all))o.code='SF';else if(/野選/.test(all))o.code='FC';else if(/失誤/.test(all))o.code='E';else if(/三振/.test(all))o.code='K';else if(/滾/.test(a))o.code='GO';else if(/飛/.test(a))o.code='FO';else if(/出局/.test(all))o.code='OUT';if(!o.code)return null;const m=all.match(/(?:打點|RBI)\s*[:：]?\s*([0-4一二兩三四])/i);if(m)o.rbi=Math.max(0,Math.min(4,chinese(m[1])));else if(o.code==='HR')o.rbi=1;return o;}
async function scheduleYear(year:number,kind:string){const j=await postSession('/schedule','/schedule/getgamedatas',{calendar:`${year}/01/01`,location:'',kindCode:normalizeKind(kind)},true);if(!j?.Success)throw new Error('CPBL 賽程查詢失敗');return typeof j.GameDatas==='string'?JSON.parse(j.GameDatas):j.GameDatas||[];}
async function box(gameSno:any,year:number,kind:string){const kc=normalizeKind(kind),path=`/box/index?gameSno=${encodeURIComponent(String(gameSno))}&kindCode=${kc}&year=${year}`;return await postSession(path,'/box/getlive',{GameSno:String(gameSno),Year:String(year),KindCode:kc},false);}
function flag(...vs:any[]){return vs.some(v=>v===true||['true','yes','y','1'].includes(String(v??'').trim().toLowerCase())||(Number.isFinite(Number(v))&&Number(v)>0));}
function completeFlags(row:any,pitching:any[],decision:string){if(!row)return{cg:false,sho:false};let cg=flag(row.IsCompleteGame,row.CompleteGame,row.CompleteGameCnt),sho=flag(row.IsShutOut,row.ShutOut,row.ShoutOut,row.ShutOutCnt,row.ShoutOutCnt);if(!cg&&['W','L'].includes(decision)){const used=(pitching||[]).filter((r:any)=>String(r.PitcherAcnt||'')&&(num(r,'PitchCnt')>0||num(r,'InningPitchedCnt')>0||num(r,'InningPitchedDiv3Cnt')>0)),sideKey=String(row.VisitingHomeType??row.VisitingHome??''),same=used.filter((r:any)=>String(r.VisitingHomeType??r.VisitingHome??'')===sideKey);if(same.length===1&&String(same[0].PitcherAcnt)===String(row.PitcherAcnt))cg=true;}if(cg&&num(row,'RunCnt')===0)sho=true;return{cg,sho};}
async function daily(acnt:string,date:string,teamCode:string,kind='A'){kind=normalizeKind(kind);const year=Number(date.slice(0,4)),games=await scheduleYear(year,kind),game=games.find((g:any)=>String(g.GameDate||'').slice(0,10)===date&&[String(g.VisitingTeamCode||'').slice(0,3),String(g.HomeTeamCode||'').slice(0,3)].includes(teamCode));if(!game)return{found:false,reason:`當天找不到此球隊的${kind==='D'?'二軍':'一軍'}例行賽`};const j=await box(game.GameSno,year,kind);if(!j?.Success)throw new Error('CPBL BOX 查詢失敗');const detail=JSON.parse(j.CurtGameDetailJson||'{}'),batting=JSON.parse(j.BattingJson||'[]'),pitching=JSON.parse(j.PitchingJson||'[]'),live=JSON.parse(j.LiveLogJson||'[]'),bat=batting.find((r:any)=>String(r.HitterAcnt)===acnt)||null,pit=pitching.find((r:any)=>String(r.PitcherAcnt)===acnt)||null,pas:any[]=[];for(let i=0;i<live.length;i++){const cur=live[i];if(String(cur.HitterAcnt)!==acnt)continue;const next=live[i+1];if(next&&String(next.HitterAcnt)===acnt)continue;const x=pa(str(cur,'BattingActionName'),str(cur,'Content'));if(x)pas.push(x);}if(bat&&pas.length){const official=Math.max(0,num(bat,'RunBattedINCnt')),sum=pas.reduce((s:number,p:any)=>s+(Number(p.rbi)||0),0);if(sum>official){let excess=sum-official;for(let i=pas.length-1;i>=0&&excess>0;i--){const x=Math.max(0,Number(pas[i].rbi)||0),cut=Math.min(x,excess);pas[i].rbi=x-cut;excess-=cut;}}}const opponent=String(detail.VisitingTeamCode||'').slice(0,3)===teamCode?detail.HomeTeamName:detail.VisitingTeamName,decision=pit?(String(detail.WinningPitcherAcnt)===acnt?'W':String(detail.LosePitcherAcnt)===acnt?'L':'ND'):'ND',cf=completeFlags(pit,pitching,decision);return{found:Boolean(bat||pit),kindCode:kind,game:{gameSno:game.GameSno,date,opponent,field:detail.FieldAbbe||game.FieldAbbe||''},hitter:bat?{plateAppearances:pas,runs:num(bat,'ScoreCnt'),hits:num(bat,'HittingCnt'),errors:num(bat,'ErrorCnt'),raw:bat}:null,pitcher:pit?{innings:`${num(pit,'InningPitchedCnt')}.${num(pit,'InningPitchedDiv3Cnt')}`,k:num(pit,'StrikeOutCnt'),bb:num(pit,'BasesONBallsCnt')+num(pit,'IntentionalBasesONBallsCnt'),h:num(pit,'HittingCnt'),hbp:num(pit,'HitBYPitchCnt'),r:num(pit,'RunCnt'),er:num(pit,'EarnedRunCnt'),pitchCount:num(pit,'PitchCnt'),cg:cf.cg,sho:cf.sho,hld:num(pit,'ReliefPointCnt')>0,sv:String(pit.IsSaveOK)==='1',bsv:String(pit.IsSaveFail)==='1',decision}:null};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({ok:false,error:'POST only'},405);if(await sha256(String(req.headers.get('x-cpbl-proxy-key')||''))!==PROXY_KEY_SHA256)return json({ok:false,error:'Forbidden'},403);try{const body=await req.json(),action=String(body.action||''),kind=normalizeKind(body.kindCode);if(action==='search-player'){const name=String(body.name||'').trim(),number=String(body.number||'').trim();if(!name||!number)return json({ok:false,error:'name/number required'},400);return json({ok:true,player:await searchPlayer(name,number)});}if(action==='suggest-players')return json({ok:true,players:await suggestPlayers(String(body.query||''),Number(body.limit)||10)});if(action==='player-profile'){const acnt=String(body.acnt||'').trim();if(!acnt)return json({ok:false,error:'acnt required'},400);return json({ok:true,player:await profile(acnt)});}if(action==='season-histories'){const acnt=String(body.acnt||'');if(!acnt)return json({ok:false,error:'acnt required'},400);return json({ok:true,...await seasonHistories(acnt)});}if(action==='season-history'){const acnt=String(body.acnt||'');if(!acnt)return json({ok:false,error:'acnt required'},400);return json({ok:true,history:await seasonHistory(acnt,kind)});}if(action==='season-stats'){const acnt=String(body.acnt||''),year=Number(body.year)||new Date().getFullYear();return json({ok:true,stats:await seasonStats(acnt,year,kind)});}if(action==='daily'){const acnt=String(body.acnt||''),date=String(body.date||''),teamCode=String(body.teamCode||'');if(!acnt||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!teamCode)return json({ok:false,error:'acnt/date/teamCode required'},400);return json({ok:true,daily:await daily(acnt,date,teamCode,kind)});}return json({ok:false,error:'unknown action'},400);}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500);}});