const APP_KEY='TyPAf0puXo-lBcrIf4Ky1wQryHaG2f4j';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const CPBL='https://cpbl.com.tw';
const MLB='https://statsapi.mlb.com/api/v1';
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36';
const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type, authorization','content-type':'application/json; charset=utf-8'};
const DBH={apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`,'content-type':'application/json'};
const KINDS=[{code:'A',competition:'regular',label:'例行賽'},{code:'D',competition:'regular',label:'二軍例行賽'},{code:'E',competition:'playoff_challenge',label:'季後挑戰賽'},{code:'C',competition:'taiwan_series',label:'總冠軍賽'}];
const reply=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:CORS});
const clean=(v:any)=>String(v??'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const score=(v:any)=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function rest(path:string,init:RequestInit={}){return await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...DBH,...(init.headers||{})}});}
async function rows(path:string){const r=await rest(path);if(!r.ok)throw new Error(`DB ${r.status}: ${await r.text()}`);const j=await r.json().catch(()=>[]);return Array.isArray(j)?j:[];}
async function upsert(table:string,row:any){const r=await rest(`${table}?on_conflict=cache_key`,{method:'POST',headers:{prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(`${table} ${r.status}: ${await r.text()}`);}
async function metric(k:string){try{await rest('rpc/increment_backend_cache_metric',{method:'POST',body:JSON.stringify({p_key:k,p_amount:1})});}catch{}}
async function fetchRetry(url:string,init:RequestInit={},attempts=3){let last:any;for(let i=1;i<=attempts;i++){try{const r=await fetch(url,init),text=await r.text();if(r.ok)return{text,headers:r.headers};last=new Error(`HTTP ${r.status}`);if(![403,429,500,502,503,504].includes(r.status))throw last;}catch(e){last=e;if(i===attempts)throw e;}await sleep(400*Math.pow(2,i-1)+Math.round(Math.random()*150));}throw last;}
function cookieHeader(headers:Headers){try{const a=(headers as any).getSetCookie?.();if(Array.isArray(a)&&a.length)return a.map((x:string)=>x.split(';')[0]).join('; ');}catch{}const raw=headers.get('set-cookie')||'';return raw.split(/,(?=\s*[^;,=\s]+=[^;,]*)/).map(x=>x.trim().split(';')[0]).filter(Boolean).join('; ');}
function csrf(html:string){return html.match(/RequestVerificationToken:\s*['\"]([^'\"]+)['\"]/)?.[1]||html.match(/name=[\"']__RequestVerificationToken[\"'][^>]*value=[\"']([^\"']+)/)?.[1]||'';}
function twDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function normKinds(v:any,def:string[]){const a=Array.isArray(v)?v:def;const out=[...new Set(a.map((x:any)=>String(x||'').toUpperCase()).filter((x:string)=>KINDS.some(k=>k.code===x)))];return out.length?out:def;}
const meta=(c:string)=>KINDS.find(x=>x.code===c)||KINDS[0];
function startRaw(r:any){return clean(r?.GameDateTimeS||r?.PreExeDate||r?.GameTime||r?.StartTime||'');}
function startMs(r:any,date=''){const raw=startRaw(r);if(raw){const iso=/[zZ]|[+-]\d{2}:?\d{2}$/.test(raw)?raw:raw.replace(' ','T')+'+08:00',ms=Date.parse(iso);if(Number.isFinite(ms))return ms;}const t=clean(r?.GameTime||r?.StartTime||'').match(/(\d{1,2}):(\d{2})/),d=String(r?.GameDate||date||'').slice(0,10);return t&&d?Date.parse(`${d}T${String(t[1]).padStart(2,'0')}:${t[2]}:00+08:00`):NaN;}
function startTime(r:any){const raw=startRaw(r),m=raw.match(/T(\d{2}:\d{2})/)||raw.match(/\b(\d{1,2}:\d{2})\b/);return m?m[1]:'';}
function status(r:any,date=''){const raw=clean(r?.GameStatusName||r?.GameStatus||r?.Status||r?.GameState||r?.GameResult||'').toLowerCase();if(/暫停|中斷|suspend|paused/.test(raw))return'suspended';if(/延|取消|保留|雨|postpon|cancel/.test(raw))return'cancelled';const s=startMs(r,date);if(Number.isFinite(s)&&Date.now()<s)return'scheduled';const end=clean(r?.GameDateTimeE||''),during=clean(r?.GameDuringTime||'');if(end||(during&&during!=='000000'))return'final';if(/結束|final|completed|game over|完賽/.test(raw))return'final';if(/進行|比賽中|live|playing|in progress/.test(raw))return'live';if(Number.isFinite(s)&&Date.now()>=s)return'live';return'scheduled';}
const TEAM:any={'中信兄弟':'中信兄弟','統一7-ELEVEn獅':'統一獅','統一獅':'統一獅','樂天桃猿':'樂天桃猿','味全龍':'味全龍','富邦悍將':'富邦悍將','台鋼雄鷹':'台鋼雄鷹'};
function game(r:any,m:any,date:string){const st=status(r,date),awayRaw=r.VisitingTeamName||r.VisitingTeam||r.VisitingTeamCode||'',homeRaw=r.HomeTeamName||r.HomeTeam||r.HomeTeamCode||'';return{away:TEAM[awayRaw]||awayRaw,home:TEAM[homeRaw]||homeRaw,awayScore:st==='scheduled'?null:score(r.VisitingScore??r.VisitingTotalScore??r.VisitingPoint),homeScore:st==='scheduled'?null:score(r.HomeScore??r.HomeTotalScore??r.HomePoint),status:st,time:startTime(r),venue:clean(r.FieldAbbe||r.FieldName||''),id:String(r.GameSno||''),kindCode:m.code,competition:m.competition,competitionLabel:m.label,statsScope:['A','D'].includes(m.code)?'season':'competition',date};}
async function scheduleSession(){const page=await fetchRetry(CPBL+'/schedule',{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'zh-TW,zh;q=.9'}}),token=csrf(page.text);if(!token)throw new Error('CPBL schedule token unavailable');const h:any={'user-agent':UA,'accept':'application/json, text/javascript, */*; q=0.01','content-type':'application/x-www-form-urlencoded; charset=UTF-8','x-requested-with':'XMLHttpRequest','referer':CPBL+'/schedule','origin':CPBL,'RequestVerificationToken':token};const cookie=cookieHeader(page.headers);if(cookie)h.cookie=cookie;return h;}
async function month(calendar:string,m:any,h:any){const out=await fetchRetry(CPBL+'/schedule/getgamedatas',{method:'POST',headers:h,body:new URLSearchParams({calendar,location:'',kindCode:m.code})}),j=JSON.parse(out.text||'{}'),rs=typeof j.GameDatas==='string'?JSON.parse(j.GameDatas||'[]'):(j.GameDatas||[]);return Array.isArray(rs)?rs:[];}
async function cpblGames(date:string,kinds:string[]){const h=await scheduleSession(),games:any[]=[];await metric('cpbl_official_schedule_requests');for(const c of kinds){const m=meta(c);let rs:any[]=[];try{rs=await month(`${date.slice(0,4)}/${date.slice(5,7)}/01`,m,h);}catch(e){console.error('CPBL kind failed',c,e);continue;}for(const r of rs.filter((x:any)=>String(x.GameDate||'').slice(0,10)===date))games.push(game(r,m,date));}return games.sort((a,b)=>String(a.time).localeCompare(String(b.time))||a.kindCode.localeCompare(b.kindCode));}
async function proxyDaily(slug:string,league:string,date:string){const r=await fetch(`${SUPABASE_URL}/functions/v1/${slug}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({appKey:APP_KEY,action:'daily-games',league,date})}),j=await r.json().catch(()=>({}));if(!r.ok||!j?.ok)throw new Error(j?.error||`${slug} ${r.status}`);return Array.isArray(j.games)?j.games:[];}
function mlbInningLabel(r:any,st:string){if(st!=='live')return'';const ls=r?.linescore||{};const inning=Number(ls?.currentInning);if(!Number.isFinite(inning)||inning<=0)return'';const state=String(ls?.inningState||ls?.inningHalf||'').toLowerCase();if(state.includes('top'))return`${inning}局上`;if(state.includes('bottom'))return`${inning}局下`;if(state.includes('middle'))return`${inning}局中`;if(state.includes('end'))return`${inning}局結束`;return`${inning}局`;}
async function mlbGames(date:string){const out=await fetchRetry(`${MLB}/schedule?sportId=1&date=${encodeURIComponent(date)}&hydrate=linescore,team,venue`,{headers:{'user-agent':UA,'accept':'application/json'}}),j=JSON.parse(out.text||'{}'),rs=(j.dates||[]).flatMap((d:any)=>d.games||[]);return rs.map((r:any)=>{const x=String(r?.status?.abstractGameState||r?.status?.detailedState||'');let st=/Final|Completed/i.test(x)?'final':/Live|In Progress|Warmup/i.test(x)?'live':'scheduled';if(/Postponed|Cancelled/i.test(x))st='cancelled';if(/Suspended/i.test(x))st='suspended';return{away:r?.teams?.away?.team?.name||'',home:r?.teams?.home?.team?.name||'',awayScore:score(r?.teams?.away?.score),homeScore:score(r?.teams?.home?.score),status:st,time:'',venue:r?.venue?.name||'',id:String(r?.gamePk||''),inningLabel:mlbInningLabel(r,st)};});}
function terminalScheduleGame(g:any){return ['final','cancelled','postponed'].includes(String(g?.status||'').toLowerCase());}
async function annotateLineupReady(league:string,date:string,games:any[]){
  if(!['CPBL','NPB'].includes(league)||!Array.isArray(games)||!games.length)return games;
  try{
    const r=await rest('rpc/get_league_lineup_ready',{
      method:'POST',
      body:JSON.stringify({p_league:league,p_game_date:date})
    });
    if(!r.ok)return games;
    const flags=await r.json().catch(()=>[]);
    if(!Array.isArray(flags)||!flags.length)return games.map((g:any)=>({...g,lineupReady:false}));
    const map=new Map(flags.map((x:any)=>[
      league==='CPBL'
        ? `${String(x?.game_id||'')}|${String(x?.kind_code||'A').toUpperCase()}`
        : String(x?.game_id||''),
      x?.lineup_ready===true
    ]));
    return games.map((g:any)=>({
      ...g,
      lineupReady:map.get(
        league==='CPBL'
          ? `${String(g?.id||'')}|${String(g?.kindCode||'A').toUpperCase()}`
          : String(g?.id||'')
      )===true
    }));
  }catch{
    return games;
  }
}
function ttl(league:string,date:string,games:any[]=[]){const today=league==='NPB'?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()):twDate();if(date<today){if(league==='MLB'){const allTerminal=games.length>0&&games.every(terminalScheduleGame);return allTerminal?Infinity:2*60*1000;}return Infinity;}if(date>today)return 6*60*60*1000;return league==='CPBL'?5*60*1000:2*60*1000;}
async function scheduleCached(league:string,date:string,kinds:string[],force=false){const scope=league==='CPBL'?kinds.slice().sort().join(','):'ALL',key=`${league}|SCHEDULE|${date}|${scope}`,stored=(await rows(`league_schedule_cache?cache_key=eq.${encodeURIComponent(key)}&select=*`))[0]||null,storedGames=Array.isArray(stored?.payload?.games)?stored.payload.games:[],rt=Date.parse(String(stored?.refresh_after||'')),frozenMlbStillMutable=league==='MLB'&&stored?.refresh_after==='infinity'&&storedGames.some((g:any)=>!terminalScheduleGame(g)),valid=stored?.payload&&!frozenMlbStillMutable&&(stored?.refresh_after==='infinity'||rt===Infinity||rt>Date.now());if(valid&&!force){await metric('schedule_cache_hits');return{games:await annotateLineupReady(league,date,storedGames),cache:{hit:true,persistent:true,scope,fetchedAt:stored.fetched_at}};}await metric('schedule_cache_misses');try{let games:any[]=[];if(league==='CPBL')games=await cpblGames(date,kinds);else if(league==='NPB')games=await proxyDaily('npb-live-games','NPB',date);else if(league==='KBO')games=await proxyDaily('kbo-live-games','KBO',date);else if(league==='MLB')games=await mlbGames(date);else throw new Error('unsupported league');const ms=ttl(league,date,games),now=Date.now(),refresh=Number.isFinite(ms)?new Date(now+ms).toISOString():'infinity';await upsert('league_schedule_cache',{cache_key:key,league,game_date:date,scope,payload:{games},fetched_at:new Date(now).toISOString(),refresh_after:refresh,source:'official',last_error:null,updated_at:new Date(now).toISOString()});return{games:await annotateLineupReady(league,date,games),cache:{hit:false,persistent:true,scope,ttlMs:Number.isFinite(ms)?ms:null,immutable:!Number.isFinite(ms)}};}catch(e){if(stored?.payload)return{games:await annotateLineupReady(league,date,storedGames),cache:{hit:true,persistent:true,stale:true,scope,error:e instanceof Error?e.message:String(e)}};throw e;}}
function normalizeTeam(v:any){return clean(v).normalize('NFKC').replace(/[・･·.\s]/g,'').toLowerCase().replace('統一7-eleven獅','統一獅');}
function sameTeam(a:any,b:any){const x=normalizeTeam(a),y=normalizeTeam(b);return !!x&&!!y&&(x===y||x.includes(y)||y.includes(x));}
function addMonths(y:number,m:number,o:number){const d=new Date(Date.UTC(y,m-1+o,1));return{year:d.getUTCFullYear(),month:d.getUTCMonth()+1};}
async function cpblNext(team:string,kinds:string[]){const today=twDate(),y=Number(today.slice(0,4)),m=Number(today.slice(5,7)),now=Date.now(),h=await scheduleSession();await metric('cpbl_official_next_game_requests');let best:any=null;for(let off=0;off<3;off++){const ym=addMonths(y,m,off),calendar=`${ym.year}/${String(ym.month).padStart(2,'0')}/01`;for(const c of kinds){let rs:any[]=[];try{rs=await month(calendar,meta(c),h);}catch{continue;}for(const r of rs){const date=String(r?.GameDate||'').slice(0,10);if(!date||date<today)continue;const g=game(r,meta(c),date);if(!sameTeam(g.away,team)&&!sameTeam(g.home,team))continue;if(['final','cancelled','postponed'].includes(String(g.status)))continue;const s=startMs(r,date);if(g.status==='live'||g.status==='suspended')return{...g,nextGameAt:Number.isFinite(s)?new Date(s).toISOString():null};if(Number.isFinite(s)&&s<now)continue;const rank=Number.isFinite(s)?s:Date.parse(`${date}T23:59:59+08:00`);if(!best||rank<best.rank)best={...g,rank,nextGameAt:Number.isFinite(s)?new Date(s).toISOString():null};}}if(best)break;}if(!best)return null;delete best.rank;return best;}
async function npbNext(team:string){const r=await fetch(`${SUPABASE_URL}/functions/v1/npb-live-games`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({appKey:APP_KEY,action:'next-game',team})}),j=await r.json().catch(()=>({}));if(!r.ok||!j?.ok)throw new Error(j?.error||`npb-live-games ${r.status}`);return j.nextGame||null;}
function nextTtl(g:any){if(!g)return 6*60*60*1000;const st=String(g.status||'').toLowerCase();if(['live','suspended'].includes(st))return 2*60*1000;const s=Date.parse(String(g.nextGameAt||''));if(!Number.isFinite(s))return 60*60*1000;const d=s-Date.now();if(d<=60*60*1000)return 5*60*1000;if(d<=24*60*60*1000)return Math.max(10*60*1000,Math.min(60*60*1000,d-60*60*1000));return 6*60*60*1000;}
async function nextCached(league:string,team:string,kinds:string[],force=false){const tk=normalizeTeam(team),scope=league==='CPBL'?kinds.slice().sort().join(','):'ALL',key=`${league}|NEXT|${tk}|${scope}`,stored=(await rows(`league_next_game_cache?cache_key=eq.${encodeURIComponent(key)}&select=*`))[0]||null,valid=stored&&Date.parse(String(stored.refresh_after||''))>Date.now();if(valid&&!force)return{nextGame:stored.payload?.nextGame||null,cache:{hit:true,persistent:true,fetchedAt:stored.fetched_at}};const nextGame=league==='CPBL'?await cpblNext(team,kinds):await npbNext(team),ms=nextTtl(nextGame),now=Date.now();await upsert('league_next_game_cache',{cache_key:key,league,team_key:tk,scope,payload:{nextGame},fetched_at:new Date(now).toISOString(),refresh_after:new Date(now+ms).toISOString(),last_error:null,updated_at:new Date(now).toISOString()});return{nextGame,cache:{hit:false,persistent:true,ttlMs:ms}};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return reply({ok:false,error:'POST only'},405);try{const body=await req.json();if(body?.appKey!==APP_KEY)return reply({ok:false,error:'Forbidden'},403);const action=String(body?.action||'daily-games'),league=String(body?.league||'').toUpperCase(),internal=req.headers.get('authorization')===`Bearer ${SERVICE_ROLE}`,force=body?.force===true&&internal;const defaultKinds=internal?['A','E','C']:['A','D','E','C'],kinds=normKinds(body?.kindCodes,defaultKinds);if(action==='next-game'){const team=String(body?.team||'').trim();if(!team||!['CPBL','NPB'].includes(league))return reply({ok:false,error:'team/league invalid'},400);return reply({ok:true,league,team,...await nextCached(league,team,league==='CPBL'?normKinds(body?.kindCodes,['A','E','C']):[],force)});}if(action!=='daily-games')return reply({ok:false,error:'unknown action'},400);const date=String(body?.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!['CPBL','NPB','KBO','MLB'].includes(league))return reply({ok:false,error:'date/league invalid'},400);return reply({ok:true,league,date,kindCodes:league==='CPBL'?kinds:undefined,...await scheduleCached(league,date,kinds,force)});}catch(e){console.error(e);return reply({ok:false,error:e instanceof Error?e.message:String(e)},500);}});